#!/bin/sh -e

# Functions to crate parent directory and then link or move
mvc() {
	mkdir -p $2
	mv $1 $2
}

lnc() {
	mkdir -p $2
	ln -sf $1 $2
}

mvc Hyprland $DESTDIR/usr/bin/
mvc hyprctl $DESTDIR/usr/bin/
mvc libwlroots.so.11032 $DESTDIR/usr/lib/

lnc $(dirname $0)/hyprland.conf ~/.config/hypr/
